AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: true
  Max: 30